name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t itskimkong/vulnalert .

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: itskimkong/vulnalert:latest
      - name: Deploy application
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
          ssh-commands: |
            ssh -p 23231 ubuntu@connect.vulnalert.app '
              docker container stop vulnalert;
              docker rm vulnalert;
              docker run --name vulnalert -p 7777:7777 --network host -d itskimkong/vulnalert:latest
            '
